### ISSUE TITLE
Add warning when bombs are about to enter the screen

### ISSUE THREAD

**Issue by ThomasHickman** [ThomasHickman/LudumDare35#1]
This is a suggested feature on Ludum Dare comments.

**Comment by jackromo** [comment]
This could be done by having an arrow appear on the left side of the screen a few moments before the bomb appears, pointing to where the bomb will appear. It could be accompanied with an 'alarm' sound effect so the player can hear it instantly.

On a similar vein, the bombs really should have a 'beeping' sound effect as their color pulsates.

**Comment by jackromo** [comment]
Has been solved by commit 0f86e49.
